# Generated by Django 4.1.3 on 2023-12-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('age_created', models.IntegerField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('prof_pic', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.artwork')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.artist')),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.artwork')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.collection'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpartyapi.user'),
        ),
    ]
